### ISSUE TITLE
После переезда на Яндекс.Коннект скрипт не работает. 

### ISSUE THREAD

**Issue by BytEvil** [alive-corpse/ydns#1]
Оно и понятно почему.... Новый API. До этого момента скрипт работал отлично! Спасибо.

**Comment by alive-corpse** [comment]
> Оно и понятно почему.... Новый API. До этого момента скрипт работал отлично! Спасибо.

Сегодня мой домен отправился следом. Читал документацию на их новое апи к коннекту. К сожалению, исправить это уже не удастся, потому что для авторизации они теперь используют Oauth 2.0, а оно требует Callback URL, которого в случае со скриптом, нет. По крайней мере, если не прикручивать к скрипту в нагрузку ещё и web-server с поддержкой https.

**Comment by alive-corpse** [comment]
Возможно, поторопился с выводами. Есть пара идей. Получится или нет - пока не знаю, но попробую.

**Comment by BytEvil** [comment]
Пока техподдержка Яндекса идет на встречу, Вернули меня на pdd.yandex. Про реализацию API DNS спросил - промолчали.

**Comment by alive-corpse** [comment]
> Пока техподдержка Яндекса идет на встречу, Вернули меня на pdd.yandex. Про реализацию API DNS спросил - промолчали.

Я сейчас в отдельной ветке переписываю скрипт на новый api. При первом запуске без параметров будет выдавать хелп, отправлять регистрировать приложение на яндекс коннект, запрашивать id, пароль, затем код подтверждения, будет создавать себе токен, сохранять внутри себя и просить перезапуска. После этого год будет работать как прежний скрипт. Когда доделаю - сказать пока не могу, но сегодня полностью разобрался с апи авторизации и с полученем списка доменов. Авторизацию почти дописал, надо будет тестировать. Но свет в конце туннеля виден. Спасибо за интерес к тому, что я пишу, это мотивирует.

**Comment by alive-corpse** [comment]
UPD: Был введён в заблуждение наличием репозитория с названием вроде dyndns yandex.connect. Там тоже ничего не работает. Похоже, тоже придётся мигрировать обратно и ждать, пока реализуют обновление dns записей. К тому моменту у меня уже будут наработки.

**Comment by BytEvil** [comment]
Вот [здесь](https://github.com/Yukioru/yandex-connect-ddns) у человека есть наработки, но проверить не могу, т.к. я сейчас на pdd. Посмотрите, если интересно :)

UPD: Там тоже Управление DNS записями в процессе разработки.

**Comment by alive-corpse** [comment]
Да, именно этот репозиторий я и смотрел. Подумал, что если он есть, то должен быть способ обновить зону через конеект. Вчера в качестве эксперимента попробовал подёргать апи пдд с авторизацией через oauth - это тоже не дало положительного результата.

**Comment by BytEvil** [comment]
Есть [еще](https://github.com/zt50tz/yandex-connect), но там управление доменами только, как я понял, просмотр, добавление и удаление доменов.

**Comment by alive-corpse** [comment]
> Есть [еще](https://github.com/zt50tz/yandex-connect), но там управление доменами только, как я понял, просмотр, добавление и удаление доменов.

Это я тоже видел. И эти функции в апи яндекс коннекта как раз есть. А вот записями управлять нельзя.

**Comment by BytEvil** [comment]
Тогда значит без вариантов, остаемся на pdd, пока API не допилят. Удачи в разработках Вам! ;)

**Comment by alive-corpse** [comment]
Спасибо огромное! Подумываю о CloudFlare или DnsPod. Идея проста - регистрируем бесплатный домен любого уровня, например, на freenom, в качестве ns серверов указываем сервера dns провайдера, который поддерживает обновление зоны через апи, делаем с  основного домена, который хостится на яндекс коннекте записи CNAME на нужные записи второго домена. Для отказоустойчивости можно взять несколько dns хостеров и обновлять параллельно. В случае необходимости - менять CNAME записи. Ну и скрипт соответствующий сделаю.

**Comment by BytEvil** [comment]
Приветствую! Хорошие [новости](https://tech.yandex.ru/pdd/doc/reference/dns-edit-docpage/)...  А pdd.yandex отключили без предупреждения...))

P.S. Промахнулся к сожалению, думал допилили API Коннекта... на деле все тоже самое. Опять в коннект мой домен перекинули.

**Comment by alive-corpse** [comment]
Доброго дня! Я для себя решил вопрос следующим образом: на моём домене был блог, я его перенёс на github pages, т.к. там был только статический контент. А для тестовых проектов взял бесплатный домен на freenom, днс перенёс на Cloud Flare и написал подобный, но ещё более навороченный скрипт для управления записями в Cloud Flare. Поддомены второно уровня прописал синеймом к бесплатному домену, а записи меняю на CloudFlare. https://github.com/alive-corpse/escflare

**Comment by BytEvil** [comment]
на cloudflare надо делегировать домен?

**Comment by alive-corpse** [comment]
Нет, достаточно изменить обслуживающий днс. Но если домен у тебя уже делегирован на яндекс, то с этим будет сложнее.

**Comment by BytEvil** [comment]
переехал на CloudFlare. Спасибо за скрипт! Работает! ;)
